In [80]:
import numpy as np
import pandas as pd

1. Define two custom numpy arrays, say A and B. Generate two new numpy
arrays by stacking A and B vertically and horizontally.

In [83]:

A = np.array([1, 2, 3, 4, 5])
B = np.array([4, 5, 6, 7, 8])
vertical_stack = np.vstack((A, B))
horizontal_stack = np.hstack((A, B))

print(vertical_stack)


In [86]:
print(horizontal_stack)

[1 2 3 4 5 4 5 6 7 8]


2. ind common elements between A and B

In [89]:
common_elements = np.intersect1d(A, B)
print(common_elements)

[4 5]


3. Extract all numbers from A which are within a specific range. eg
between 5 and 10

In [92]:
filtered_numbers = A[(A >= 5) & (A <= 10)]
print(filtered_numbers)

[5]


4. Filter the rows of iris_2d that has petallength (3rd column) > 1.5
and sepallength (1st column) < 5.0

In [95]:
# 4. Filter iris dataset
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
filtered_iris = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]


In [97]:
print(filtered_iris)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


5. From df filter the 'Manufacturer', 'Model' and 'Type' for every
20th row starting from 1st (row 0)


In [100]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [102]:
# Select the desired columns
selected_columns = ['Manufacturer', 'Model', 'Type']

# Filter rows and columns
filtered_cars = df.loc[df.index[::20], selected_columns]

In [104]:
print(filtered_cars)

   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


6. Replace missing values in Min.Price and Max.Price columns with
their respective mean.

In [107]:
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

In [109]:
import pandas as pd

# Load the dataset
df = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

# Replace missing values in Min.Price and Max.Price with their means
df['Min.Price'] = df['Min.Price'].fillna(df['Min.Price'].mean())
df['Max.Price'] = df['Max.Price'].fillna(df['Max.Price'].mean())

# Verify the changes
print(df[['Min.Price', 'Max.Price']].head())
print(df[['Min.Price', 'Max.Price']].isnull().sum())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091
Min.Price    0
Max.Price    0
dtype: int64


In [111]:
# 7. Get rows with row sum > 100
random_df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
rows_greater_than_100 = random_df[random_df.sum(axis=1) > 100]

In [113]:
print(rows_greater_than_100)

     0   1   2   3
0   32  29  37  10
3   22  33  38  35
7   39  29  28  21
9   25  35  35  13
13  39  38  34  36
14  22  31  30  35
